####################################################
# Control change (continuous controller) mappings. #
####################################################

# Note that it is not necessary to loop messages from one unit back to the same unit.
# Doing so will not have an effect.

# Internal channel 0
[[channel]]
device = "Self"
[channel.transmitted]
66 = {Pianoteq = "sostenuto/CV"}
67 = {Pianoteq = "una corda/CV"}


# Internal channel 1
[[channel]]
device = "Reface CP"
[channel.bilateral]
[channel.transmitted]
3 = {Pianoteq = "tremolo depth"}
9 = {Pianoteq = "tremolo rate"}
12 = {Pianoteq = "delay"}
13 = {Pianoteq = "flanger"}
14 = {Pianoteq = "wah depth"}
15 = {Pianoteq = "wah rate"}
20 = {Pianoteq = "chorus depth"}
21 = {Pianoteq = "chorus rate"}
22 = {Pianoteq = "phaser intensity"}
23 = {Pianoteq = "phaser rate"}
24 = {Pianoteq = "delay feedback"}
25 = {Pianoteq = "delay time"}
26 = {Pianoteq = "flanger depth"}
27 = {Pianoteq = "flanger delay"}
64 = {Pianoteq = "sustain/CV"}
70 = {Pianoteq = "wah"}
91 = {Pianoteq = "reverb duration"}
92 = {Pianoteq = "tremolo"}
93 = {Pianoteq = "chorus"}
95 = {Pianoteq = "phaser"}
[channel.received]
sustain = []
sostenuto = [{control = 66, channel = 0}]
"soft pedal" = [{control = 67, channel = 0}]
modwheel = [{control = 1, channel = 2}]
expression = []
volume = []
"local control" = [{control = 122, channel = 0}]

# Internal channel 2
[[channel]]
device = "Minilogue XD"
[channel.bilateral]
"CVin1" = 118
"CVin2" = 119
[channel.transmitted]
118 = {}
119 = {}
[channel.received]
"CVin1" = []
"CVin2" = []
"CVin1+" = [{control = 66, channel = 0}]
"CVin2+" = [{control = 64, channel = 1}]
"CVin1-" = [{control = 67, channel = 0}]
"CVin2-" = []


# Internal channel 3
[[channel]]
device = "Unused"

# Internal channel 4
[[channel]]
device = "Unused"

# Internal channel 5
[[channel]]
device = "Unused"

# Internal channel 6
[[channel]]
device = "Unused"

# Internal channel 7
[[channel]]
device = "Unused"

# Internal channel 8
[[channel]]
device = "Unused"

# Internal channel 9
[[channel]]
device = "Unused"

# Internal channel 10
[[channel]]
device = "Unused"

# Internal channel 11
[[channel]]
device = "Unused"

# Internal channel 12
[[channel]]
device = "Unused"

# Internal channel 13
[[channel]]
device = "Unused"

# Internal channel 14
[[channel]]
device = "Unused"

# Internal channel 15
[[channel]]
device = "Unused"