####################################################
# Control change (continuous controller) mappings. #
####################################################

# Note that it is not necessary to loop messages from one unit back to the same unit.
# Doing so will not have an effect.

# Internal channel 0
[[channel]]
device = "Self"
[channel.transmitted]
64 = {Pianoteq = "sustain/CV"} # should be in reface channel
4 = {Pianoteq = "Leslie/CV"}
36 = {Pianoteq = "Leslie/CV"}


# Internal channel 1
[[channel]]
device = "Reface CP"
[channel.transmitted]
64 = {Pianoteq = "sustain/CV"}

# Internal channel 2
[[channel]]
device = "Minilogue XD"
[channel.transmitted]
118 = {} # CV in 1
119 = {} # CV in 2
[channel.received]
"CV in 1" = []
"CV in 2" = [{control = 64, channel = 0}] # change to ch 1 later


# Internal channel 3
[[channel]]
device = "Unused"

# Internal channel 4
[[channel]]
device = "Unused"

# Internal channel 5
[[channel]]
device = "Unused"

# Internal channel 6
[[channel]]
device = "Unused"

# Internal channel 7
[[channel]]
device = "Unused"

# Internal channel 8
[[channel]]
device = "Unused"

# Internal channel 9
[[channel]]
device = "Unused"

# Internal channel 10
[[channel]]
device = "Unused"

# Internal channel 11
[[channel]]
device = "Unused"

# Internal channel 12
[[channel]]
device = "Unused"

# Internal channel 13
[[channel]]
device = "Unused"

# Internal channel 14
[[channel]]
device = "Unused"

# Internal channel 15
[[channel]]
device = "Unused"