####################################################
# Control change (continuous controller) mappings. #
####################################################

# Avoid:
# - bank select messages (0 and 32)
# - data entry (6 and 38)
# - brightness (74)
# - high-resolution velocity prefix (88)
# - data increment/decrement (96 and 97)
# - non-registered parameter number (98 and 99)
# - registered parameter number (100 and 101)
# - channel mode messages (120-127)

# Internal channel 0
[[channel]]
device = "Self"
[channel.transmitted]
66 = {Pianoteq = "sostenuto/CV"}
67 = {Pianoteq = "una corda/CV"}


# Internal channel 1
[[channel]]
device = "Reface CP"
[channel.bilateral]
sustain = 64
tremolo = 92
"tremolo depth" = 3
"tremolo rate" = 9
wah = 70
"wah depth" = 14
"wah rate" = 15
chorus = 93
"chorus depth" = 20
"chorus speed" = 21
phaser = 95
"phaser depth" = 22
"phaser speed" = 23
"digital delay" = 12
"digital delay depth" = 24
"digital delay time" = 25
"analog delay" = 13
"analog delay depth" = 26
"analog delay time" = 27
reverb = 91
[channel.transmitted]
3 = {Pianoteq = "tremolo depth"}
9 = {Pianoteq = "tremolo rate"}
12 = {Pianoteq = "delay"}
13 = {Pianoteq = "flanger"}
14 = {Pianoteq = "wah depth"}
15 = {Pianoteq = "wah rate"}
20 = {Pianoteq = "chorus depth"}
21 = {Pianoteq = "chorus rate"}
22 = {Pianoteq = "phaser intensity"}
23 = {Pianoteq = "phaser rate"}
24 = {Pianoteq = "delay feedback"}
25 = {Pianoteq = "delay time"}
26 = {Pianoteq = "flanger depth"}
27 = {Pianoteq = "flanger delay"}
64 = {Pianoteq = "sustain/CV"}
70 = {Pianoteq = "wah"}
91 = {Pianoteq = "reverb duration"}
92 = {Pianoteq = "tremolo"}
93 = {Pianoteq = "chorus"}
95 = {Pianoteq = "phaser"}
[channel.received]
sustain = []
sostenuto = [{control = 66, channel = 0}]
"soft pedal" = [{control = 67, channel = 0}]
modwheel = [{control = 1, channel = 2}]
expression = []
volume = []

# Internal channel 2
[[channel]]
device = "Minilogue XD"
[channel.bilateral]
"Y+" = 1
"Y-" = 2
"CVin1" = 118
"CVin2" = 119
[channel.transmitted]
1 = {}
2 = {}
118 = {}
119 = {}
[channel.received]
"Y+" = []
"Y-" = []
"CVin1" = []
"CVin2" = []
"CVin1+" = [{control = 66, channel = 0}]
"CVin2+" = [{control = 64, channel = 1}]
"CVin1-" = [{control = 67, channel = 0}]
"CVin2-" = []


# Internal channel 3
[[channel]]
device = "Unused"

# Internal channel 4
[[channel]]
device = "Unused"

# Internal channel 5
[[channel]]
device = "Unused"

# Internal channel 6
[[channel]]
device = "Unused"

# Internal channel 7
[[channel]]
device = "Unused"

# Internal channel 8
[[channel]]
device = "Unused"

# Internal channel 9
[[channel]]
device = "Unused"

# Internal channel 10
[[channel]]
device = "Unused"

# Internal channel 11
[[channel]]
device = "Unused"

# Internal channel 12
[[channel]]
device = "Unused"

# Internal channel 13
[[channel]]
device = "Unused"

# Internal channel 14
[[channel]]
device = "Unused"

# Internal channel 15
[[channel]]
device = "Unused"