####################
# General Settings #
####################

[palette] # rgb values between 0 and 1
black = [0.0, 0.0, 0.0]
white = [1.0, 1.0, 1.0]
red = [1.0, 0.0, 0.0]
orange = [1.0 ,0.5, 0.0]
yellow = [1.0, 1.0, 0.0]
green = [0.0, 1.0, 0.0]
cyan = [0.0, 1.0, 1.0]
blue = [0.0, 0.0, 1.0]
magenta = [1.0, 0.0, 1.0]

[QjackCtl]
patchbay = "/home/pi/microtonOS/config/qjackctl.xml"

[Carla]
headless = false
project = "/home/pi/microtonOS/config/carla.carxp"

[Pianoteq]
version = "Pianoteq 8 STAGE"
standalone = true
headless = false
midimapping = "midimapping"
preset0 = "/home/pi/microtonOS/config/Pianoteq/Presets/My Presets/NY Steinway D.fxp"
files = []
directories = []

[tuneBfree]
standalone = true
directory = "/home/pi/microtonOS/config/tuneBfree/"
midimapping = "midimapping.toml"
presets = "drawbars.pgm"

["Surge XT"]
standalone = false

[dexed]
standalone = false

["Reface CP"]
channel = 0

["Minilogue XD"]
channel = 0
