#########################################
# Presets, tunings and layouts,         #
# for the MTS-ESP master in microtonOS. #
#########################################

# Tuning presets.
#
# - name is a string describing the tuning.
#   It does not affect the sound.
#   (For MTS sysex messages, the string is converted to 16 ASCII characters.)
#   Mandatory but could be set to "" for multiple entries.
#
# - class determines the colour scheme
#   and functionality of the footswitch and the manuals.
#   Mandatory.
#   It is one of the following strings:
#   - "edo". white keys -> red pads, black keys -> orange pads.
#     Manual 1 follows the tuning, while manual 2 is one note below.
#     Pressing the footswitch is the same as pressing (and releasing) all the keyswitches.
#     Releasing the footswitch returns the keyswitches to their previous state.
#   - "octaveless". white -> red, black -> magenta.
#     Otherwise the same.
#   - "Hertz". white -> blue, black -> magenta.
#     Otherwise the same.
#   - "ombak". white -> blue, black -> green.
#     Each note is doubled and the pairs are fine-tuned further.
#     Manual 1 has the odd members of the pairs, while manual 2 has the even.
#     The footswitch plays both members of the pairs simultaneously.
#   - "uneven". white -> yellow, black -> green.
#     For notes without keyswitches, the two manuals are tuned the same.
#     By default, manual 2 is the same as 1 and the footswitch does nothing.
#
# - tonality finetunes the colour scheme further by turning some of the leds off.
#   Mandatory.
#   It is one of the following strings:
#   - "micro" all pads of corresponding to manual 1 are lit.
#   - "standard". All pads corresponding to black keys are turned off.
#   - "macro". Keys in odd equaves are turned off.
# 
# - tones is a table that determines the tuning.
#   Mandatory.
#   - unit is "cents" or "Hertz"
#   - distance is a number or a table.
#     A number represents the distance between two adjacent tones in the tuning.
#     For tables:
#     - cumulative = true or false.
#     - cycle is an array of numbers representing distances of varying sizes that are repeated across the tuning.
#
# - root is a table that determines the reference point of the tuning.
#   Default is {note = 69, frequency = 440.0}.
#   - frequency is a pitch in Hertz.
#   - note is a midi note (0 to 127) to which the frequency is assigned.
#
# - halberstadt is a table describing the tuning of piano/organ keys.
#   Default is {mapping = [0,1,2,3,4,5,6,7,8,9,10,11,12], boundary = "c"}
#   - boundary is a string, "c", "c#", ..., "b", representing the key at which the cycle for the mapping starts.
#   - mapping is an array of integers, nan, pairs, and longer tuples.
#     The last element is the first element of the next cycle.
#     Recommended length of the mapping is 13 elements.
#     - An integer represents a number of tones in the tuning.
#       Recommended integers are those causing the white keys or the black or both
#       to correspond to a  "musically meaningful" scale.
#     - A nan means that the korresponding key is silent and not mapped to any tone.
#     - In a pair, the first element is the default.
#       Pressing (and releasing) a keyswitch sets the corresponding key to the next value.
#       Pressing again resets it to the first.
#     - For n-tuples, you need to press the keyswitch n times to return to the default value.
#
# - dilation is the suggested dilation for isomorphic layouts.
#   Default is 3.
#   Recommended value is the number of tones to reach the minor third.
#
# - ombak is a table only used for the "ombak" class.
#   Default is {pengumbang = 0.0, pengisep = 0.0}
#   Recommended values are < 15.0Hz.
#   - pengisep is the frequency in Hertz by which even notes have been lowered.
#   - pengumbang is the frequency in Hertz by which odd notes have been raised.
#
# - uneven is a table only used for the "uneven" class.
#   Default is {manual2 = nan, footswitch = nan},
#   which means that manual 2 is the same as 1 and the footswitch does nothing.
#   - manual 2 sets the mapping for manual 2 when the footswitch is off.
#   - footswitch sets the mapping for manual2 when the footswitch is on.
#   The mappings are in the same format as for "halberstadt".
#   If an element is an array, then it must be the same length as the corresponding element in "halberstadt.mapping".
#   The boundary equals "halberstadt.boundary"

[[tuning]]
name = "12edo"
class = "edo"
tonality = "standard"
tones = {distance = 100, unit = "cents"}

[[tuning]]
name = "5 Drumonics"
class = "uneven"
tonality = "macro"
tones.distance = {cycle = [514, 639, 884, 1052, 1189], cumulative = true}
tones.unit = "cents"
root = {note = 70, frequency = 440}
halberstadt = {mapping = [0, nan, nan, 1, nan, 2, nan, nan, 3, nan, 4, nan, 5], boundary = "a#"}
dilation = 1

[[tuning]]
name = "Hexany"
class = "uneven"
tonality = "macro"
tones.distance = {cycle = [272, 386, 655, 888, 869, 1200], cumulative = true}
tones.unit = "cents"
halberstadt = {mapping = [0, nan, 1, nan, 2, nan, 3, nan, 4, nan, 5, nan, 6], boundary = "c#"}
root = {note = 70, frequency = 440.0}
dilation = 1

[[tuning]]
name = '43Hz Bb=413Hz'
class = "Hertz"
tonality = "macro"
tones = {distance = 43.0, unit = "Hertz"}
root = {note = 70, frequency = 413.0}
halberstadt = {mapping = [0, 1, 2, nan, nan, 3, nan, 4, nan, 5, nan, nan, 6], boundary = "c#"}
dilation = 1

[[tuning]]
name = "Narrow 13ed3"
class = "octaveless"
tonality = "macro"
tones = {distance = 146.3, unit = "cents"}
halberstadt = {mapping = [0, nan, 1, nan, 2, 3, nan, 4, nan, 5, nan, 6, 7], boundary = "c"}
dilation = 2

[[tuning]]
name = "10Hz A=440Hz"
class = "Hertz"
tonality = "macro"
tones = {distance = 20.0, unit = "Hertz"}
halberstadt = {mapping = [0, nan, 1, nan, 2, 3, nan, 4, nan, 5, nan, 6, 7], boundary = "c"}
dilation = 2

[[tuning]]
name = "9edo+8Hz"
class = "ombak"
tonality = "micro"
tones = {distance = 133.3, unit = "cents"}
root = {note = 70, frequency = 440.0}
ombak = {pengumbang = 0.0, pengisep = 8.0}
halberstadt = {mapping = [0, 2, nan, 4, 6, 8, 10, nan, 12, nan, 14, 16, 18], boundary = "c"}
dilation = 4

[[tuning]]
name = "10edo-10Hz"
class = "ombak"
tonality = "micro"
tones = {distance = 120.0, unit = "cents"}
ombak = {pengumbang = 10.0, pengisep = 0.0}
halberstadt = {mapping = [0, 2, 4, 6, nan, 8, 10, 6, 14, 16, 18, nan, 20], unit = "c"}
dilation = 4

# [[tuning]]
# name = "Dekany"
# class = "uneven"
# tonality = "macro"
# tones.distance = {cycle = [84, 204, 267, 471, 583, 702, 786, 969, 1018, 1200], cumulative = true}
# tones.unit = "cents"}
# halberstadt = {mapping = [0, 1, 2, 3, 4, nan, 5, 6, 7, 8, nan, 9, 10], boundary = "f"}
# dilation = 3

[[tuning]]
name = "11 Huis"
class = "uneven"
tonality = "macro"
tones.distance = {cycle = [231.2, 266.9, 315.6, 386.3, 498.0,  582.5, 702.0, 813.7, 884.4,  968.8, 1200.0], cumulative = true}
tones.unit = "cents"
halberstadt = {mapping = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, nan, 11], boundary = "a"}
dilation = 3

[[tuning]]
name = "11 Harmonics"
class = "uneven"
tonality = "macro"
tones.distance = {cycle = [105.0, 203.9, 297.5, 386.3, 470.8, 551.3, 702.0, 840.5, 968.8, 1088.3, 1200.0], cumulative = true}
tones.unit = "cents"
halberstadt = {mapping = [0, 1, 2, 3, 4, 5, 6, 7, 8, nan, 9, 10, 11], boundary = "f"}
dilation = 3

[[tuning]]
name = "11 Subharmonics"
class = "uneven"
tonality = "macro"
tones.distance = {cycle = [111.7, 231.2, 359.5, 498.0, 648.7, 729.2, 813.7, 902.5, 996.1, 1095.0, 1200.0], cumulative = true}
tones.unit = "cents"
halberstadt = {mapping = [0, 1, 2, nan, 3, 4, 5, 6, 7, 8, 9, 10, 11], boundary = "f"}
dilation = 3

[[tuning]]
name = "12edo+-3Hz"
class = "ombak"
tonality = "micro"
tones = {distance = 100, unit = "cents"}
ombak = {pengumbang = 3.0, pengisep = 3.0}
halberstadt = {mapping = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24], boundary = "c"}
dilation = 6

[[tuning]]
name = "Wide 8edPhi"
class = "octaveless"
tonality = "standard"
tones = {distance = 833.1, unit = "cents"}

[[tuning]]
name = "10Hz A=441Hz"
class = "Hertz"
tonality = "standard"
tones = {distance = 10.0, unit = "Hertz"}

[[tuning]]
name = "Wide 8ed3/2"
class = "octaveless"
tonality = "micro"
tones = {distance = 87.7, unit = "cents"}
halberstadt = {mapping = [0, 1, 2, 3, [4,5], 6, 7, 8, 9, 10, 11, [12,13], 14], boundary = "c"}

[[tuning]]
name = "14edo"
class = "edo"
tonality = "micro"
tones = {distance = 85.7, unit = "cents"}
halberstadt = {mapping = [0, 1, 2, 3, [4,5], 6, 7, 8, 9, 10, 11, [12,13], 14], boundary = "c"}
dilation = 3

[[tuning]]
name = "15edo"
class = "edo"
tonality = "micro"
tones = {distance = 80.0, unit = "cents"}
halberstadt = {mapping = [0, [2,1], 3, 4, 5, 6, [8,7], 9, [11,10], 12, 13, 14, 15], boundary = "c#"}
dilation = 3

[[tuning]]
name = "Narrow 9ed3/2"
class = "octaveless"
tonality = "micro"
tones = {distance = 78.0, unit = "cents"}
halberstadt = {mapping = [0, 1, [2,3], 4, 5, 6, [7,8], 9, 10, [11,12], 13, [14,15], 16], boundary = "d"}
dilation = 4

[[tuning]]
name = "16edo"
class = "edo"
tonality = "micro"
tones = {distance = 75.0, unit = "cents"}
halberstadt = {mapping = [[0,1], 2, 3, 4, [5,6], [8,7], 9, 10, 11, 12, 13, [15,14], 16], boundary = "c"}
dilation = 4

[[tuning]]
name = "17edo"
class = "edo"
tonality = "micro"
tones = {distance = 70.6, unit = "cents"}
halberstadt = {mapping = [0, [1,2], 3, 4, [5,6], 7, [8,9], 10, [11,12], 13, 14, [15,16], 17], boundary = "c"}
dilation = 4

[[tuning]]
name = "17 Pythagoreans"
class = "uneven"
tonality = "micro"
tones.distance = {cycle = [90.2, 180.4, 203.9, 294.1, 384.4, 407.8, 498.0, 588.3, 678.5, 702.0, 792.2, 882.4, 905.9, 996.1, 1086.3, 1176.5, 1200.0], cumulative = true}
tones.unit = "cents"
halberstadt = {mapping = [0, [1,2], 3, 4, [6,5], 7, [8,9], 10, [11,12], 13, 14, [15,16], 17], boundary = "c"}
uneven.manual2 = [0, 1, 3, 4, 5, 7, 8, 10, 11, 13, 14, 15, 17]
uneven.footswitch = [0, 2, 3, 4, 6, 7, 9, 10, 12, 13, 14, 16, 17]
dilation = 4

[[tuning]]
name = "Narrow 8ed4/3"
class = "octaveless"
tonality = "micro"
tones = {distance = 62.3, unit = "cents"}
halberstadt = {mapping = [0, [2,1], 3, [5,4], [6,7], 8, [10,9], 11, [13,12], 14, [16,15], [17,18], 19], boundary = "c"}
dilation = 5

[[tuning]]
name = "19 from 41edo"
class = "uneven"
tonality = "micro"
tones.distance = {cycle = [175.6, 204.9, 234.1, 322.0, 351.2, 380.5, 409.8, 497.6, 614.6, 702.4, 848.8, 878.0, 907.3, 936.6, 1024.4, 1082.9, 1112.2, 1200.0], cumulative = true}
tones.unit = "cents"
halberstadt = {mapping = [0, 1, [2,3], 5, [6,7,4], 8, 9, 10, 11, [13,14,12], 15, [16,17], 18], boundary = "f"}
uneven.manual2 = [0, 1, 2, 5, [4,6,4], 8, 9, 10, 11, [12,13,12], 15, 16, 18]
uneven.footswitch = [0, 1, 3, 5, [7,7,6], 8, 9, 10, 11, [14,14,13], 15, 17, 18]
dilation = 5

[[tuning]]
name = "19edo"
class = "edo"
tonality = "micro"
tones = {distance = 63.2, unit = "cents"}
halberstadt = {mapping = [0, [2,1], 3, [5,4], [6,7], 8, [10,9], 11, [13,12], 14, [16,15], [17,18], 19], boundary = "c"}
dilation = 5

[[tuning]]
name = "19 from 48edo"
class = "uneven"
tonality = "micro"
tones.distance = {cycle = [75.0, 100.0, 200.0, 300.0, 325.0, 375.0, 400.0, 500.0, 575.0, 600.0, 700.0, 775.0, 800.0, 900.0, 1000.0, 1025.0, 1075.0, 1100.0, 1200.0], cumulative = true}
tones.unit = "cents"
halberstadt = {mapping = [0, [2,1], 3, [4,5], [6,7], 8, [10,9], 11, [13,12], 14, [15,16], [17,18], 19], boundary = "c"}
uneven.manual2 = [0, 1, 3, 4, 6, 8, 9, 11, 12, 14, 15, 17, 19]
uneven.footswitch = [0, 2, 3, 5, 7, 8, 10, 11, 13, 14, 16, 18, 19]
dilation = 4

# [[tuning]]
# name = "Eikosany"
# class = "Uneven"
# tonality = "micro"
# tones.distance = {cycle = [53.3, 84.5, 165.0, 203.9, 266.9, 368.9, 431.9, 470.8, 551.3, 582.5, 635.8, 702.0, 786.4, 818.2, 867.0, 968.8, 1017.6, 1049.4, 1133.8, 1200.0], cumulative = true}
# tones.unit = "cents"
# halberstadt = {mapping = [0, [2,1], [4,3], 5, [6,7], 8, [10,9], [12,11], [14,13], [16,14], 17, [18,19], 20], boundary = "c"}
# dilation = 5
# # cycle in rational numbers: [33/32, 21/20, 11/10, 9/8, 7/6, 99/80, 77/60, 21/16, 11/8, 7/5, 231/160, 3/2, 63/40, 77/48, 33/20, 7/4, 9/5, 11/6, 77/40, 2/1]

[[tuning]]
name = "22edo"
class = "edo"
tonality = "micro"
tones = {distance = 54.5, unit = "cents"}
halberstadt = {mapping = [0, [2,1], 3, [4,5], [7,6], [9,8], [10,11], [13,12], [14,15], [16,17], [18,19], [20,21], 22], boundary = "c"}
dilation = 6

[[tuning]]
name = "22 from 53edo"
class = "uneven"
tonality = "micro"
tones.distance = {cycle = [90.6, 113.2, 181.1, 203.8, 294.3, 317.0, 384.9, 407.5, 498.1, 588.7, 611.3, 679.2, 701.9, 792.5, 815.1, 883.0, 905.7, 996.2, 1018.9, 1086.8, 1109.4, 1200.0], cumulative = true}
tones.unit = "cents"
halberstadt = {mapping = [0, [1,2], [3,4], [5,6], [7,8], 9, [10,11], [13,12], [14,15], [17,16], [18,19], [20,21], 22], boundary = "c"}
uneven.manual2 = [0, 1, 3, 5, 7, 9, 10, 12, 14, 16, 18, 20, 22]
uneven.footswitch = [0, 2, 4, 6, 8, 9, 11, 13, 15, 17, 19, 21, 22]
dilation = 6

[[tuning]]
name = "24edo"
class = "edo"
tonality = "micro"
tones = { distance = "50.0", unit = "cents"}
halberstadt = {mapping = [[0,-1], [2,1], [4,3], [6,5], [7,8], [10,9], [12,11], [14,13], [16,15], [18,17], [20,19], [21,22], [24,23]], boundary = "c"}
dilation = 6

[[tuning]]
name = "29edo"
class = "edo"
tonality = "micro"
tones = {distance = 41.4, unit = "cents"}
halberstadt = {mapping = [0, [2,3], 5, [7,8], [9,10], 12, [14,15], 17, [19,20], 22, [24,25], [26,27], 29], boundary = "c"}
dilation = 7

[[tuning]]
name = "31edo"
class = "edo"
tonality = "micro"
tones = {distance = 38.7, unit = "cents"}
halberstadt = {mapping = [0, [3,2], [5,6], [8,7], [10,9], 13, [16,15], [18,19], [21,20], [23,24], [26,25], [28,27], 31], boundary = "c"}
dilation = 8

[[tuning]]
name = "Narrow 20ed3/2"
class = "octaveless"
tonality = "micro"
tones = {distance = 35.1, unit = "cents"}
halberstadt = {mapping = [[0,-1], [3,2], [6,5], [9,8], [11,10], [14,13], [17,16], [20,19], [23,22], [25,24], [28,27], [1,30], [34,33]], boundary = "c"}
dilation = 9

[[tuning]]
name = "Wide 20ed3/2"
class = "octaveless"
tonality = "micro"
tones = {distance = 35.1, unit = "cents"}
halberstadt = {mapping = [0, [5,4], 6, 9, 10, [15,14], 19, 20, [25,24], 28, 26, 30, 35], boundary_tone = 'e'}
dilation = 9

# Isomorphic layout presets.
# NOT YET INCORPORATED!
#
# - name is a string describing the layout.
#   It does not affect the layout.
#   Mandatory but could be set to "" for multiple entries.
#
# - class is "semivariant" or "invariant".
#   In "semivariant", the axes are independent, whereas in "invariant", they are parameterized.
#   Mandatory.
#   - semivariant. basis [dilation, constant]
#   - invariant. basis [dilation, f3d]
#
# - changeofbasis is the matrix which, when multiplied with the basis, yields [x, y] coordinates.
#   On hexagonal grids, y is the diagonal to the left (120° from x).
#   Mandatory.
#
# - split is a table explaining the behaviour of the isomorphic layout in split mode.
#   Default is nan, i.e. no split mode whatsoever.
#   - line is "dash", "slash", or "backslash" describing the shape of the line between the split.
#   - axis is 0 or 1. If 0, the two mini layouts are arranged along the x axis.
#     If 1, along the y axis.

[[layout]]
name = "Exquis"
class = "semivariant"
changofbasis = [[0,1], [1,0]]
split = {line = "dash", axis = 0}

[[layout]]
name = "Harmonic Table"
class = "semivariant"
changeofbasis = [[2,1], [-1,0]]
split = {line = "dash", axis = 1}

[[layout]]
name = "Exquis 2"
class = "semivariant"
changeofbasis = [[0,1], [2,0]]
split = {line = "dash", axis = 0}

[[layout]]
name = "Harmonic Table 2"
class = "semivariant"
changeofbasis = [[2,2], [-1,0]]
split = {line = "dash", axis = 1}

[[layout]]
name = "Wicki-Hayden"
class = "invariant"
changeofbasis = [[3,-2], [-2,1]]
split = {line = "backslash", axis = 0}

[[layout]]
name = "Jankó"
class = "invariant"
changeofbasis = [[0,1], [1,-2]]
split = {line = "slash", axis = 1}